server.port=8089

spring.datasource.url=${DB_URL:jdbc:postgresql://daring-faun-20078.jxf.gcp-asia-south1.cockroachlabs.cloud:26257/defaultdb?sslmode=require}
spring.datasource.username=${DB_USER:edu_tst6_gmail_com}
spring.datasource.password=${DB_PASSWORD:QvgzUiIDzHcSHhcFUYODiA}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true