package com.mindcare.backend.model;

public enum NotificationType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_DECLINED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,
    NEW_MESSAGE,
    ASSESSMENT_ASSIGNED,
    DOCUMENT_UPLOADED
}
